// scripts/generateExamplesIndex.mjs
//
// Regenerates docs/AI_EXAMPLES_INDEX.md — the index of the CANONICAL example
// corpus: curated, explicitly-approved reference implementations per pattern
// (a rate-limited auth API route, a sync server+client pair, the tryCatch
// pattern, a page+component+middleware). The AI copies these as templates.
//
// Distinct from AI_RUNBOOKS.md: the runbooks cite a deterministic FIRST-match
// real file ("here is an example"); this corpus is the curated, annotated
// "here is THE right shape, and WHY" — reviewed snippets, not arbitrary matches.
//
// Source of truth: docs/examples/<slug>.md (frontmatter `pattern` + a canonical
// code block + a "why this shape" annotation). The README/template seed
// (0000-template.md) is skipped. The MCP tools `list_examples` / `get_example`
// query the result.
//
// Pure-Node ESM. Deterministic (no timestamps). KEEP IN SYNC with
// packages/create-luckystack-app/template/scripts/generateExamplesIndex.mjs.

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, "..");
const EXAMPLES_DIR = path.join(REPO_ROOT, "docs", "examples");
const OUTPUT_FILE = path.join(REPO_ROOT, "docs", "AI_EXAMPLES_INDEX.md");

const safe = async (promise) => { try { return [null, await promise]; } catch (error) { return [error, null]; } };
const safeSync = (fn) => { try { return [null, fn()]; } catch (error) { return [error, null]; } };
const toPosix = (p) => p.replaceAll("\\", "/");
const relFromRepo = (abs) => toPosix(path.relative(REPO_ROOT, abs));

const FRONTMATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---/;

const parseInlineArray = (raw) => {
  const trimmed = raw.trim();
  if (!trimmed.startsWith("[")) return null;
  const inner = trimmed.replace(/^\[/, "").replace(/\]$/, "").trim();
  if (!inner) return [];
  return inner.split(",").map((s) => s.trim().replace(/^['"]|['"]$/g, "")).filter(Boolean);
};

const parseFrontmatter = (src) => {
  const match = src.match(FRONTMATTER_RE);
  if (!match) return null;
  const out = {};
  for (const line of match[1].split(/\r?\n/)) {
    const m = line.match(/^([A-Za-z_][\w-]*)\s*:\s*(.*)$/);
    if (!m) continue;
    const asArray = parseInlineArray(m[2].trim());
    out[m[1]] = asArray !== null ? asArray : m[2].trim().replace(/^['"]|['"]$/g, "");
  }
  return out;
};

const extractSection = (src, heading) => {
  const re = new RegExp(`^##\\s+${heading}\\s*$([\\s\\S]*?)(?=^##\\s|$(?![\\r\\n]))`, "mi");
  const m = src.match(re);
  if (!m) return null;
  const body = m[1].trim();
  if (!body) return null;
  const firstPara = [];
  for (const line of body.split(/\r?\n/)) {
    const t = line.trim();
    if (t.startsWith("```")) break;
    if (!t) { if (firstPara.length > 0) break; else continue; }
    firstPara.push(t.replace(/^[-*]\s*/, ""));
  }
  return firstPara.length > 0 ? firstPara.join(" ") : null;
};

const scanExamples = async () => {
  const [readErr, entries] = await safe(fs.readdir(EXAMPLES_DIR, { withFileTypes: true }));
  if (readErr) return [];
  const rows = [];
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".md")) continue;
    if (entry.name === "0000-template.md" || entry.name === "README.md") continue;
    const abs = path.join(EXAMPLES_DIR, entry.name);
    const [err, src] = await safe(fs.readFile(abs, "utf8"));
    if (err || src === null) continue;
    const front = parseFrontmatter(src) ?? {};
    const slug = entry.name.replace(/\.md$/, "");
    rows.push({
      slug,
      file: relFromRepo(abs),
      pattern: typeof front.pattern === "string" ? front.pattern : slug,
      title: typeof front.title === "string" ? front.title : slug.replaceAll("-", " "),
      tags: Array.isArray(front.tags) ? front.tags : [],
      whenToUse: extractSection(src, "When to use"),
    });
  }
  return rows.sort((a, b) => a.pattern.localeCompare(b.pattern));
};

const escapeCell = (value) => String(value ?? "").replaceAll("|", "\\|").replaceAll(/\r?\n/g, " ").trim();

const renderTable = (header, rows) => {
  if (rows.length === 0) return "_(none)_";
  const out = [`| ${header.join(" | ")} |`, `| ${header.map(() => "---").join(" | ")} |`];
  for (const row of rows) out.push(`| ${row.map(escapeCell).join(" | ")} |`);
  return out.join("\n");
};

const buildDocument = (rows) => {
  const parts = [];
  parts.push("# Canonical Examples Index");
  parts.push("");
  parts.push("> Auto-generated by `scripts/generateExamplesIndex.mjs` — regenerate via `npm run ai:examples`.");
  parts.push("> Hand edits will be overwritten — edit the example files in `docs/examples/` instead.");
  parts.push(">");
  parts.push("> Curated, explicitly-approved reference implementations. When building one of these patterns,");
  parts.push("> open the matching example and copy its SHAPE — it is the reviewed-correct template, not an");
  parts.push("> arbitrary first match. Query via the MCP tools `list_examples` / `get_example`.");
  parts.push("");
  parts.push(`## Examples (${rows.length})`);
  parts.push("");
  if (rows.length === 0) {
    parts.push("_(none yet — add curated examples under `docs/examples/`. On an existing project the AI offers to seed the corpus from the real, reviewed routes/pages.)_");
    parts.push("");
    return parts.join("\n");
  }
  parts.push(
    renderTable(
      ["Pattern", "Title", "When to use", "Tags", "File"],
      rows.map((r) => [
        `\`${r.pattern}\``,
        r.title,
        r.whenToUse ?? "—",
        r.tags.length ? r.tags.join(", ") : "—",
        `\`${r.file}\``,
      ]),
    ),
  );
  parts.push("");
  return parts.join("\n");
};

const main = async () => {
  const rows = await scanExamples();
  const document = buildDocument(rows);
  const [mkErr] = await safe(fs.mkdir(path.dirname(OUTPUT_FILE), { recursive: true }));
  if (mkErr) { console.error(`[ai:examples] failed to ensure docs directory: ${mkErr.message}`); process.exit(1); }
  const [writeErr] = await safe(fs.writeFile(OUTPUT_FILE, document, "utf8"));
  if (writeErr) { console.error(`[ai:examples] failed to write ${OUTPUT_FILE}: ${writeErr.message}`); process.exit(1); }
  console.log(`[ai:examples] generated ${relFromRepo(OUTPUT_FILE)} (${rows.length} example${rows.length === 1 ? "" : "s"})`);
};

const [runErr] = await safe(main());
if (runErr) {
  safeSync(() => console.error(`[ai:examples] fatal: ${runErr.stack ?? runErr.message ?? runErr}`));
  process.exit(1);
}
